version: 2
updates:
  # Actualizaciones para GitHub Actions en la raíz
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
      timezone: "Europe/Berlin"
    groups:
      all:
        patterns:
          - "*"
