blank_issues_enabled: false
contact_links:
  - name: Preguntas sobre proyecto-nuevo
    url: https://github.com/moranricardo/proyecto-nuevo/discussions
    about: Para dudas generales o guía de uso, por favor abre un hilo en la sección de Discusiones del proyecto.
