name: Monitoreo de Gerrit

on:
  workflow_dispatch: # Permite ejecución manual desde la web
  schedule:
    - cron: '0 */6 * * *' # Se ejecuta automáticamente cada 6 horas

jobs:
  check-changes:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar el repositorio
        uses: actions/checkout@v7

      - name: 🟢 Configurar Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '26'

      - name: 🚀 Ejecutar Auditoría de Gerrit
        run: node index.cjs check
