name: Validador de Integridad (Maat)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v7

    - name: Configurar Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 26

    - name: Instalar Dependencias
      run: npm install --production || echo "No hay dependencias pesadas"

    - name: Validar Sintaxis del Orquestador
      run: node index.cjs check
