name: Ra Pulse CI
on: [push, workflow_dispatch]
jobs:
  orchestrate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Prueba Minima
        run: |
          node -v
          ls -R
          node src/rapulse.js
